version: '3'

volumes:
  djuris_legal_local_postgres_data: {}
  djuris_legal_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: djuris_legal_local_django
    container_name: djuris_legal_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: djuris_legal_production_postgres
    container_name: djuris_legal_local_postgres
    volumes:
      - djuris_legal_local_postgres_data:/var/lib/postgresql/data
      - djuris_legal_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: djuris_legal_local_docs
    container_name: djuris_legal_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./djuris_legal:/app/djuris_legal:z
    ports:
      - '9000:9000'
    command: /start-docs

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: djuris_legal_local_node
    container_name: djuris_legal_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
