# Generated by Django 4.2.6 on 2023-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Causa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("caratula", models.CharField(max_length=100)),
                ("expediente", models.IntegerField()),
                ("año", models.IntegerField()),
                ("actora", models.CharField(max_length=50)),
                ("demandada", models.CharField(max_length=50)),
                ("objeto", models.CharField(choices=[("AL", "Alimentos"), ("CP", "Cuidado Personal")])),
            ],
        ),
    ]
