# Generated by Django 4.2.6 on 2023-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("causas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="causa",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="causa",
            name="objeto",
            field=models.CharField(
                choices=[("AL", "Alimentos"), ("CP", "Cuidado Personal"), ("DV", "Divorcio Vincular")]
            ),
        ),
    ]
