# Generated by Django 4.2.6 on 2023-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("causas", "0002_alter_causa_id_alter_causa_objeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="causa",
            name="fuero",
            field=models.CharField(choices=[("Fam", "Familia"), ("Civ", "Civil")], default=None),
        ),
        migrations.AlterField(
            model_name="causa",
            name="objeto",
            field=models.CharField(
                choices=[("AL", "Alimentos"), ("CP", "Cuidado Personal"), ("DV", "Divorcio Vincular")], default=None
            ),
        ),
    ]
