# Generated by Django 4.2.6 on 2023-11-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("causas", "0003_causa_fuero_alter_causa_objeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="causa",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
